// For streaming
export const SAVE_PERFORMANCE_ID = "SAVE_PERFORMANCE_ID";
export const LOAD_SPEECHES = "LOAD_SPEECHES";
export const SAVE_CURRENT_SPEECH_ID = "SAVE_CURRENT_SPEECH_ID";
export const CHANGE_STREAMING_STATUS = "CHANGE_ISPLAYING_STATUS";
export const CHANGE_STREAM_STATE_TO_INITIAL = "CHANGE_STREAM_STATE_TO_INITIAL";
export const CHANGE_CURRENT_PLAYBACK_TIME = "CHANGE_CURRENT_PLAYBACK_TIME";
export const CHANGE_CONNECTING_STATUS = "CHANGE_CONNECTING_STATUS";

// For Sidebar
export const CHANGE_CURRENT_TAB_ID = "CHANGE_CURRENT_TAB_ID";

// For AudioUpload
export const CHANGE_IS_NEW_FILES_LOADED = "CHANGE_IS_NEW_FILES_LOADED";
export const ADD_NEW_FILES_NAME = "ADD_NEW_FILES_NAME";
export const DELETE_NEW_FILES_NAME = "DELETE_NEW_FILES_NAME";
export const CHANGE_AUDIO_UPLOAD_TO_INITIAL_STATE = "CHANGE_TO_AUDIO_UPLOAD_INITIAL_STATE";
